# -*- coding: utf-8 -*-
"""WEEK1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j4hFasBQJUCVSrfV3-nQ6dwwCQG_gYuK
"""

num1 = int(input("Enter a number to check odd or even "))
if num1 %2  ==0:
  print(num1 ,"num1 is positive")
else:
  print(num1,"is odd")

marks = int(input("Enter your marks"))

if marks > 90:
  print("A+")
elif marks > 70 :
   print("A")

elif marks > 50:
   print("B")
else:
  print("fail")

num1 = int(input("Enter num 1 "))
num2 = int(input("Enter num 2 "))
num3 = int(input("Enter num 3 "))

if(num1 > num2):
  if(num1> num3):
    print(num1,"num 1 is greater:")
# else:
#   print(num3)
else:
  if(num2 > num2):
    print(num2,"num 2 is greater:")
  else:
    print(num3,"num 3 is greater:")

# print 1 1 to 10 with help  of forLoop
# for i in range(1,11):
#   print(i)
#   print(i,end = '')

for i in range(5 , 51, 5):
   print(i)

num = int(input("Enter number you want a table of"))
print(num ,"* 1",i,"==",5 * i)
print(i,'en = i')

while (i < 11):
  print(i)

num1 = int(input('Enter num 1: '))
num2 = int(input('Enter num 2: '))
for i in range(num1,num2+1):
  if i % 2 == 0:
    print(i ,"is even:")
  else:
    print(i," is odd:")

L = [7,8,9,5,2,7,55,105,109]
Lb = []

for i in L:
  if i % 5 == 0:
    break
  Lb.append(i)
print(Lb)

